AWSTemplateFormatVersion: '2010-09-09'
Resources:
  FastAiAsgLaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: ami-bc508adc
      SpotPrice: "0.80"
      KeyName: "aws-key"
      SecurityGroups: 
        - !ImportValue FastAiSecurityGroup 
      InstanceType: p2.xlarge
      BlockDeviceMappings:
          - DeviceName: "/dev/sda1"
            Ebs:
              VolumeSize: '128'
              VolumeType: 'gp2'
      UserData:
        Fn::Base64: !Sub |
           #!/bin/bash -xe
           cd home/ubuntu
           wget https://raw.githubusercontent.com/kahgeh/courses/master/setup/Lesson1Setup.sh
           bash Lesson1Setup.sh
           echo "[Unit]
            Description=Jupyter Notebook

            [Service]
            Type=simple
            PIDFile=/run/jupyter.pid
            # Step 1 and Step 2 details are here..
            # ------------------------------------
            ExecStart=/home/ubuntu/anaconda2/bin/jupyter-notebook --config=/home/ubuntu/.jupyter/jupyter_notebook_config.py
            User=ubuntu
            Group=ubuntu
            WorkingDirectory=/home/ubuntu/nbs
            Restart=always
            RestartSec=10
            #KillMode=mixed

            [Install]
            WantedBy=multi-user.target
            " >> /usr/lib/systemd/system/jupyter.service

            sudo systemctl enable jupyter.service
            sudo systemctl daemon-reload
            sudo systemctl restart jupyter.service
  FastAiElasticLoadBalancer:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      Subnets:
      - !ImportValue FastAiSubnetId
      Listeners:
      - LoadBalancerPort: '8888'
        InstancePort: '8888'
        Protocol: HTTP
      ConnectionDrainingPolicy:
        Enabled: 'true'
        Timeout: '60'              
  FastAiAutoScalingServerGroup: 
      Type: AWS::AutoScaling::AutoScalingGroup
      Properties: 
        AvailabilityZones: 
        - 'us-west-2a'
        LaunchConfigurationName: !Ref FastAiAsgLaunchConfig
        LoadBalancerNames:
          - !Ref FastAiElasticLoadBalancer
        MinSize : 1
        MaxSize : 1
        VPCZoneIdentifier:
        - !ImportValue FastAiSubnetId
