AWSTemplateFormatVersion: '2010-09-09'
Resources:
  FastAiAsgLaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: ami-8c4288f4
      SpotPrice: "0.90"
      KeyName: "aws-key"
      SecurityGroups: 
        - !ImportValue FastAiSecurityGroup 
      InstanceType: p2.xlarge
      BlockDeviceMappings:
          - DeviceName: "/dev/sda1"
            Ebs:
              VolumeSize: '128'
              VolumeType: 'gp2'
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          cd home/ubuntu
          cd fastai
          git pull
          conda env update
          pip install kaggle-cli --upgrade
          curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
          sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-debian-jessie-prod jessie main" > /etc/apt/sources.list.d/microsoft.list'
          apt-get update
          apt-get install -y powershell          
  FastAiElasticLoadBalancer:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      Subnets:
      - !ImportValue FastAiSubnetId
      Listeners:
      - LoadBalancerPort: '8888'
        InstancePort: '8888'
        Protocol: HTTP
      ConnectionDrainingPolicy:
        Enabled: 'true'
        Timeout: '60'              
  FastAiAutoScalingServerGroup: 
      Type: AWS::AutoScaling::AutoScalingGroup
      Properties: 
        AvailabilityZones: 
        - 'us-west-2a'
        LaunchConfigurationName: !Ref FastAiAsgLaunchConfig
        LoadBalancerNames:
          - !Ref FastAiElasticLoadBalancer
        MinSize : 1
        MaxSize : 1
        VPCZoneIdentifier:
        - !ImportValue FastAiSubnetId
