AWSTemplateFormatVersion: '2010-09-09'
Resources:
  FastAiAsgLaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: ami-bc508adc
      SecurityGroups: 
        - !ImportValue FastAiSecurityGroup 
      InstanceType: p2.xlarge
      BlockDeviceMappings:
          - DeviceName: "/dev/sda1"
            Ebs:
              VolumeSize: '128'
              VolumeType: 'gp2'
  FastAiElasticLoadBalancer:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      AvailabilityZones:
        Fn::GetAZs: 'us-west-2'
      Listeners:
      - LoadBalancerPort: '8888'
        InstancePort: '8888'
        Protocol: HTTP
      ConnectionDrainingPolicy:
        Enabled: 'true'
        Timeout: '60'              
  FastAiAutoScalingServerGroup: 
      Type: AWS::AutoScaling::AutoScalingGroup
      Properties: 
        AvailabilityZones: 
          Fn::GetAZs: Ref! AWS::Region
        LaunchConfigurationName: !Ref FastAiAsgLaunchConfig
        LoadBalancerNames:
          - FastAiElasticLoadBalancer
        MinSize : 1
        MaxSize : 1
