AWSTemplateFormatVersion: '2010-09-09'
Resources:
  FastAiAsgLaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: ami-bc508adc
      SpotPrice: "0.80"
      KeyName: "aws-key"
      SecurityGroups: 
        - !ImportValue FastAiSecurityGroup 
      InstanceType: p2.xlarge
      BlockDeviceMappings:
          - DeviceName: "/dev/sda1"
            Ebs:
              VolumeSize: '128'
              VolumeType: 'gp2'
      UserData:
        Fn::Base64: !Sub |
           
  FastAiElasticLoadBalancer:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      Subnets:
      - !ImportValue FastAiSubnetId
      Listeners:
      - LoadBalancerPort: '8888'
        InstancePort: '8888'
        Protocol: HTTP
      ConnectionDrainingPolicy:
        Enabled: 'true'
        Timeout: '60'              
  FastAiAutoScalingServerGroup: 
      Type: AWS::AutoScaling::AutoScalingGroup
      Properties: 
        AvailabilityZones: 
        - 'us-west-2a'
        LaunchConfigurationName: !Ref FastAiAsgLaunchConfig
        LoadBalancerNames:
          - !Ref FastAiElasticLoadBalancer
        MinSize : 1
        MaxSize : 1
        VPCZoneIdentifier:
        - !ImportValue FastAiSubnetId
